language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
jdk:
  - openjdk7
  - oraclejdk7
before_install: "git clone https://github.com/geomajas/geomajas-build-tools target/geomajas-build-tools"
install: "travis_retry mvn install -DskipTests=true -B -V --settings target/geomajas-build-tools/settings.xml"
script: "travis_retry mvn verify -B -V --settings target/geomajas-build-tools/settings.xml"
env: MAVEN_OPTS="-XX:MaxPermSize=256m"
