language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "git clone https://github.com/geomajas/geomajas-build-tools target/geomajas-build-tools"
jdk:
  - oraclejdk7
cache:
  directories:
  - $HOME/.m2
install: mvn install -B -q -V -Dgwt.compiler.localWorkers=1 -DskipTests=true --settings target/geomajas-build-tools/settings.xml
script: mvn test -B -q -V
env: MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=256m"
